[mgr]
mouse_events = [ "click", "scroll", "touch", "move", "drag" ]

[opener]
xdg = [
	{
		run = 'xdg-open "$@"',
		desc = 'Abrir con xdg-open',
		for = "linux"
	}
]

[[plugin.prepend_fetchers]]
# id    = "git" # Remove if Yazi > v26.1.22
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
# id    = "git" # Remove if Yazi > v26.1.22
url   = "*/"
run   = "git"
group = "git"

[[plugin.prepend_previewers]]
url = "*/"
run = "eza-preview"

