[mgr]
mouse_events = [ "click", "scroll", "touch", "move", "drag" ]

[opener]
edit = [
	{ run = '${EDITOR:-micro} "$@"', desc = "Editar", block = true, for = "linux" }
]

micro = [
	{ run = 'micro "$@"', desc = "Editar con Micro", block = true, for = "linux" }
]
glow = [
	{ run = 'glow -p "$@"', desc = "Ver con Glow", block = true, for = "linux" }
]

reveal = [
	{ run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" }
]
xdg = [
	{ run = 'xdg-open "$@"', desc = "Abrir con xdg-open", for = "linux" }
]

[open]
prepend_rules = [
	# Markdown primero: glow por defecto, con nvim/micro como alternativas en Shift+O
	{ url = "*.md",     use = [ "glow", "edit", "micro" ] },
	{ mime = "image/*", use = [ "xdg", "reveal" ] },
	{ mime = "text/*",  use = [ "edit", "micro", "xdg" ] },
	{ url = "*",        use = [ "edit", "micro", "xdg", "reveal" ] },
]

[[plugin.prepend_fetchers]]
# id    = "git" # Remove if Yazi > v26.1.22
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
# id    = "git" # Remove if Yazi > v26.1.22
url   = "*/"
run   = "git"
group = "git"

[[plugin.prepend_previewers]]
url = "*/"
run = "eza-preview"

[preview]
max_width = 800
max_height = 600
