# Configuración básica de Tmux
# ~/.config/tmux/tmux.conf

# Cambiar el prefijo a Ctrl-a
unbind C-b
set-option -g prefix C-a
bind-option C-a send-prefix

# Habilitar soporte de ratón
set -g mouse on

# Ajustar índices
set -g base-index 1
setw -g pane-base-index 1

# Color de la barra de estado
set -g status-style bg=black,fg=white
